Add event display (2d & 3d) dashApp
bfonta/bye_splits pull request #11
Opened 2023-01-25 17:47 UTC by mchiusi

The added files allow to visualise events from `/eos/user/b/bfontana/FPGAs/new_algos/skim_small_electrons_0PU_bc_stc_hadd.root` `ROOT` file.
Similar files can be used: the needed variables are efficiently stored in `bye_splits/data_handle/config.yaml`.  It's possible to change the input file by changing the `EOSDataFolder` variable in `bye_splits/utils/params.py`.

The main script is `bye_splits/plot/display_plotly/main.py`. Its Python execution allows to launch a dashApp running on `http://llruicms01.in2p3.fr:8004/`.

Files to get data from the `ROOT` file are stored in `bye_splits/data_handle` folder.
Files to analyse each single event are in `bye_splits/plot/display_plotly/` folder. The definition of the figures and production of 2 and 3D plots is present as well.

From the web app it's possible to:
- visualise 3D events;
- visualise 2D events, layer by layer;

Then, for each 2D or 3D case:
- to change event (if not specified, an event is chosen from the event list present in the `ROOT` file). If the chosen event is not found an error will occur, but the GUI is still on;
- to modify the energy threshold (in MIP_T);
- to visualise the clustered and non clustered trigger cells of each event.

This is how an event should appear in the 3D visualisation mode:
![Screenshot 2023-01-25 at 18 36 07](https://user-images.githubusercontent.com/67897021/214639479-94beebb8-8c18-4a7e-a9aa-3eb5f95f4bde.png)

2023-01-26 22:22 UTC, bfonta commented
Very nice addition, we are getting quite close of having a workable event display! Some comments: 

- Have you checked the code also works for photons samples? Also:
    1. it is better not to include a path to a data input file that will be likely changed in the future
    2. the file is not part of the repository, so it might be better not to mention it explicitly
    3. the path itself will likely change in the future
- In the same line, you mention many files by name and how they are used. As soon as those files are modified, this PR's text will become outdated. If you really want to include mentions to specific code elements use a link _to the last commit you are including_ (not to a branch, as this also gets updated often)
- Could you please add units to the axis labels? Where can we find the axis (plus label) for the color code?
- Can you include a picture showing the energy threshold slider you mention?
- I would like to see the above for the full geometry, as a check that everything is as expected (like what was done in #5 )

2023-01-26 22:26 UTC, bfonta commented on bye_splits/data_handle/event.py
> +import numpy as np
```numpy``` here is not required, as the method also exists in ```awkward```

2023-01-26 22:51 UTC, bfonta reviewed
- Could you add docstrings to most functions, and some comments?
- Sometimes you reuse some parameters; try to define those in one place only.

2023-01-26 22:51 UTC, bfonta commented on bye_splits/data_handle/event.py
> +    def get_event_number(self):
What information do you want exactly? If you want all event id's present in the input files, then the function should be called ```get_event_numbers```, and please include a docstring. I also suggest you to look into python properties (used for getters and setters).

2023-01-26 22:51 UTC, bfonta commented on bye_splits/data_handle/event.py
> +    def provide_event_number(self):
You pick events at random? What is the point?

2023-01-26 22:51 UTC, bfonta commented on bye_splits/data_handle/geometry.py
> +            #if self.logger is not None:
Why did you comment the above? The logger can be useful for debugging.

2023-01-26 22:51 UTC, bfonta commented on bye_splits/plot/display_plotly/event_processing.py
> +                                            zerolinecolor="white",),),
Since all the ```dict```s are the same you could define just one on top; if only part of the parameters are common you can use the ```**dict``` syntax.

2023-01-26 22:51 UTC, bfonta commented on bye_splits/plot/display_plotly/main.py
> +parser = argparse.ArgumentParser()
In general is good practice to put the parser in a ```if __name__ == "__main__":``` block.

2023-01-26 22:51 UTC, bfonta commented on bye_splits/plot/display_plotly/main.py
> +if __name__ == '__main__':
Very likely we will need to adapt the port and host names. Can you please add them in the parser, and use the values above as default (for the moment)?

2023-01-26 22:51 UTC, bfonta commented on bye_splits/plot/display_plotly/plot_event.py
> +        listdata.append(datum)
This looks horrendously inefficient. Are we sure there is no way to directly feed a pandas dataframe to a ```Scatter3D``` call? I would not mind reworking a bit the dataframe structure if it helps (the current structure is ```bokeh``` friendly, but we could add a ```plotly``` friendly version as well).

2023-01-26 22:51 UTC, bfonta commented on bye_splits/plot/display_plotly/plot_event.py
> +        listdata.append(datum)
Same as before.

2023-01-27 11:17 UTC, mchiusi commented on bye_splits/data_handle/event.py
> +import numpy as np
AttributeError: module 'awkward' has no attribute 'unique'

2023-01-27 11:21 UTC, mchiusi commented on bye_splits/data_handle/event.py
> +    def get_event_number(self):
Name changed and docstring added.

2023-01-27 11:24 UTC, mchiusi commented on bye_splits/data_handle/event.py
> +    def provide_event_number(self):
As explained above when you click the button 'change event', a random event is chosen among the list returned by `get_event_numbers`.
In this way you can visualise some events and see for example if the clustering algorithm is working fine or not. In the next future JB and I plan to random select some of the 'pathological events'.

2023-01-27 12:42 UTC, mchiusi commented on bye_splits/data_handle/geometry.py
> +            #if self.logger is not None:
As you prefer :)

2023-01-27 13:31 UTC, mchiusi commented on bye_splits/plot/display_plotly/event_processing.py
> +                                            zerolinecolor="white",),),
Right. Correct

2023-01-27 13:35 UTC, mchiusi commented on bye_splits/plot/display_plotly/plot_event.py
> +        listdata.append(datum)
At the moment I don't see any other way to do it. You have to define each polygon and add its trace to the figure.
Any suggestion is of course well accepted!

2023-01-27 15:28 UTC, bfonta commented on bye_splits/data_handle/event.py
> +import numpy as np
You are definitely right; I got confused with [this PR](https://github.com/scikit-hep/awkward/issues/1104), which is still open.
However, for this case, you should be able to do what you want with [pandas.unique](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.unique.html).

2023-01-27 15:29 UTC, bfonta commented on bye_splits/data_handle/event.py
> +    def get_event_number(self):
Ok, thank you. Looking forward to see those in your next commit.

2023-01-27 15:32 UTC, bfonta commented on bye_splits/data_handle/event.py
> +    def provide_event_number(self):
I see, it is an interesting addition I had not though of. Please then change the title of the buttom for something including the word "random" (at least for the moment).

2023-01-27 15:35 UTC, bfonta commented on bye_splits/plot/display_plotly/plot_event.py
> +        listdata.append(datum)
Can't you do something [along these lines](https://github.com/bfonta/bye_splits/blob/69d9fb94cde562ce694d80a8b78f06f071e6b0a2/bye_splits/plot/join/app.py#L36-L45)?
Perhaps @itehle has some suggestion?

2023-01-29 16:05 UTC, bfonta commented on bye_splits/data_handle/event.py
> +        ds = ak.to_dataframe(ds)
There is no need to convert to a pandas dataframe when you only want the event numbers, which you can access with ```ds.event```.

2023-02-01 08:18 UTC, mchiusi commented on bye_splits/data_handle/event.py
> +    def provide_event_number(self):
Done

2023-02-01 08:29 UTC, mchiusi commented on bye_splits/data_handle/event.py
> +        ds = ak.to_dataframe(ds)
Righ

2023-02-01 08:30 UTC, mchiusi commented on bye_splits/data_handle/event.py
> +import numpy as np
Solved

2023-02-01 08:50 UTC, mchiusi commented on bye_splits/plot/display_plotly/main.py
> +if __name__ == '__main__':
Good idea, thanks!

2023-02-01 08:51 UTC, mchiusi commented on bye_splits/plot/display_plotly/main.py
> +parser = argparse.ArgumentParser()
parser in `if __name__ == "__main__":` block now!

2023-02-01 09:29 UTC, mchiusi commented on bye_splits/plot/display_plotly/plot_event.py
> +        listdata.append(datum)
I'm using `plotly.graph_objects`. The only two options to do it through this library are reported [here](https://plotly.com/python/shapes/):
- adding more traces
- interrupting the series with `None`

Maybe we could change library.. we can discuss

2023-02-01 14:08 UTC, bfonta commented on bye_splits/plot/display_plotly/plot_event.py
> +        listdata.append(datum)
Looking at the link you provided, indeed using ```None``` seems reasonable (it won't work with "holes" within the same shape, but we should not have those :crossed_fingers:). 
Given the above, I do not think we need to change the current data format, that works out of the box and would require a small transformation for ```plotly```. 

I would modify [this function](https://github.com/bfonta/bye_splits/blob/470158873f3924514269094fdf569100005dfaab/bye_splits/data_handle/geometry.py#L116), adding the ```library='plotly'``` possibility, and performing the necessary modifications to ```diamond_x/y``` and ```hex_x/y```. Namely, you likely do not want the list of lists per row (like [this](https://github.com/bfonta/bye_splits/blob/470158873f3924514269094fdf569100005dfaab/bye_splits/data_handle/geometry.py#L240) which, by the way, is quite slow and raising issues during deployment). Feel also free to add a conversion to a uni-dimensional list with interspersed ```None```s, making sure it is only done when ```library='plotly'```.

Let me know what you think. @itehle feel also free to comment, as this addition might be useful for you sooner or later.

2023-02-02 16:11 UTC, mchiusi commented on bye_splits/plot/display_plotly/plot_event.py
> +        listdata.append(datum)
@bfonta I changed a bit the geometry functions (see last commit).

2023-02-02 16:49 UTC, bfonta requested changes
Essentially everything is fine. Just add the remaining details and we can merge this.

2023-02-02 16:49 UTC, bfonta commented on bye_splits/data_handle/event.py
> +        print(self.inpath)
please remove

2023-02-02 16:49 UTC, bfonta commented on bye_splits/data_handle/geometry.py
> +            data[self.var.c] = np.full(len(data), "#8a2be2")
IIUC, ``` #8a2be2  ``` is enough, as the broadcasting is done automatically both by ```pandas``` and by ```awkward```, as shown below:

```shell
(base) bruno@pc:~  $ python
Python 3.9.5 (default, Jun  4 2021, 12:28:51) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> df = pd.DataFrame({'x': [0,1,2], 'y': [4,5,6]})
>>> df
   x  y
0  0  4
1  1  5
2  2  6
>>> df['z'] = 7.
>>> df
   x  y    z
0  0  4  7.0
1  1  5  7.0
2  2  6  7.0
>>> import awkward as ak
>>> df2 = ak.Array({'x': [0,1,2], 'y': [4,5,6]})
>>> df2
<Array [{x: 0, y: 4}, {...}, {x: 2, y: 6}] type='3 * {x: int64, y: int64}'>
>>> df2['z'] = 7.
>>> df2
<Array [{x: 0, y: 4, z: 7}, ..., {x: 2, ...}] type='3 * {x: int64, y: int64...'>
>>> df2
<Array [{x: 0, y: 4, z: 7}, ..., {x: 2, ...}] type='3 * {x: int64, y: int64...'>
>>> df2['z']
<Array [7, 7, 7] type='3 * float64'>
```

2023-02-02 16:49 UTC, bfonta commented on bye_splits/plot/display_plotly/main.py
> +        df_cluster    = df_sel.loc[df_sel.tc_cluster_id != 0]
I believe ```loc``` is not required.

2023-02-02 16:49 UTC, bfonta commented on bye_splits/plot/display_plotly/main.py
> +        df_cluster    = df_sel.loc[df_sel.tc_cluster_id != 0]
same as before

2023-02-02 16:49 UTC, bfonta commented on bye_splits/plot/display_plotly/plot_event.py
> +_all_ = [ 'EventData' ]
remove ```'EventData'```, since it refers to a different file; please read about ```__all__``` in general, might be useful to know

2023-02-02 16:49 UTC, bfonta commented on bye_splits/utils/params.py
> +EOSDataFolder = '/eos/user/m/mchiusi/visualization/'#'/eos/user/b/bfontana/FPGAs/new_algos/'
Keep it as it was or, much better, find a general approach that works for everybody. Probably the first, as our time is limited, but you decide!

2023-02-03 16:11 UTC, bfonta approved these changes
For the future: the full geometry in 3D is unbearably slow (much slower than for 2D, as expected, given the larger number of rendered objects and the naturally inefficient way of adding objects to a ```plotly``` graph). The 2D visualization is also a bit too slow to be used comfortably when all trigger cells are on.
It is to see whether the event displays remain usable with pile-up; this will likely be extremely dependent on the initial trigger cell energy cut. The visualization for events without pile-up is fine, so we will for the moment avoid early optimizations that are hopefully not required.

2023-02-03 16:12 UTC, merged