Reconstruction chain rewrite: make it standalone
bfonta/bye_splits pull request #18
Opened 2023-02-06 22:48 UTC by bfonta

_Goal:_ Rewrite the reconstruction chain in order to make it independent of any algorithm. This will bring also bring some efficiency improvement, given that some tasks are currently doing more operations than required due to legacy code related to the trigger cell bin shifting algorithm (under ```bye_splits/iterative_optimization.py```).

The geometry was extended to provide multiple events at once and more variables (including generated- and cluster-related). It continues to output ```pandas``` dataframes for simplicity (this might be changed in the future in case it becomes too slow due to pile-up).
A running script example was included under ```bye_splits/run_chain.py```.
The old tasks were kept in backup (```bye_splits/tasks_old/```) while the legacy trigger cell shift algorithm is also not rewritten taking into accounts the changes in this PR.

Linked to #15 .

2023-02-27 14:59 UTC, isehle submitted a review, later dismissed
Quite a lot of work, wow! I don't see anything that would cause conflicts with my work.

2023-02-27 15:13 UTC, bfonta commented
@mchiusi Please, do not convert draft PRs to the "ready" state unless you authored them.
@isehle Sorry to bother, I will let you know once this PR is ready to be merged.

2023-03-01 10:12 UTC, isehle commented on bye_splits/utils/params.py
>  EOSDataFolder = '/eos/user/b/bfontana/FPGAs/new_algos/'
Instead of setting the EOSDataFolder directly, could you do something like [this](https://github.com/isehle/bye_splits/blob/1f444d601818d22b1cfaf4d0d092cdb90e55cdfa/bye_splits/utils/params.py#L64)—I added a "user" option to ```parsing``` so that the folder on ```/eos``` can be set automatically starting from there.

2023-03-01 10:15 UTC, isehle reviewed
This really looks great and I'm looking forward to seeing how the new reco chain compares to the last one! I mentioned a few couple minor suggestions but otherwise this seems ready to me.

2023-03-01 14:37 UTC, bfonta commented on bye_splits/utils/params.py
>  EOSDataFolder = '/eos/user/b/bfontana/FPGAs/new_algos/'
Valid point, but hard to fix.
In my opinion configuration parameters should as much as possible be static, so that one can know the state of execution of some code just by looking at the configuration. The best option would be to use the shell ```${USER}```, but local usernames are not guaranteed to match ```eos``` usernames (mine are different, for instance).
Using your approach implies forcing the client to specify their username every time, which is a pain. I could set a default, but we would go to a situation similar to what we have now.
I've chosen a simple compromise (quite possibly not ideal): defining an anonymous function that takes the username as input

```python
EOSStorage = lambda u: os.path.join('/eos/user', u[0], u, 'FPGAs/new_algos')
```

This avoids specifying a default, and is tidy. To use it (works for any username):

``` python
storage = EOSStorage('bfontana')
```

2023-03-01 14:38 UTC, bfonta commented on bye_splits/tasks/fill.py
> +        df1 = df1[(df1.gen_eta>1.7) & (df1.gen_eta<2.8)]
Definitely agree.
I've taken this chance to rewrite the configuration, removing unused variables and moving all configuration dictionaries to the new ```bye_splits/tasks/config.yaml```.

2023-03-01 14:48 UTC, isehle commented on bye_splits/utils/params.py
>  EOSDataFolder = '/eos/user/b/bfontana/FPGAs/new_algos/'
In principal that's true, though I get around it (maybe in a bit messy way) by wrapping the python call in a bash script with the ```$user``` variable set inside before it's called. The lambda function looks totally sufficient though!

2023-03-01 14:52 UTC, isehle submitted a review, later dismissed
Looks ready to me!

2023-03-01 14:52 UTC, bfonta commented
Thank you @isehle for the review and approval.
@mchiusi, could you share your thoughts?

2023-03-02 11:06 UTC, mchiusi requested changes
Great Bruno! I have just added a few minor suggestions.

In general the code seems ready to me: in addition to the reco chain, some bugs have been fixed and now an event has much more information than before!
Moreover, I don't see any conflict with my display code.

2023-03-02 12:22 UTC, bfonta commented on bye_splits/data_handle/config.yaml
>  varEvents:
updated

2023-03-02 12:26 UTC, bfonta commented on bye_splits/data_handle/data_handle.py
> +    ds_tc = ds_tc[tc_keep.values()]
I doubt that it makes a difference (unless ```rename()``` is badly implemented, which would be surprising), but from a code flow point of view it makes sense. Updated in the next commit.

2023-03-02 12:33 UTC, bfonta commented on bye_splits/data_handle/config.yaml
> +    id: 'good_tc_cluster_id'
For clarification, the cluster ID's are defined as the IDs of their TC seed (an ```unsigned int```, just like you mention). 
You are right in saying that the value does not correspond to the id of the cells, but rather to the id assigned to the cluster the TC belongs to. Changing the name to ```cl``` would be confusing given that we are using the sanme name for cluster-related variables. I've thus used ```idcl```. Updated in the next commit.

2023-03-02 12:48 UTC, bfonta commented on bye_splits/data_handle/config.yaml
> +    id: 'good_tc_cluster_id'
Interestingly, I've now realized I am not using the variable anywhere in the reconstruction chain. IIRC the merge between cluster and TC dataframes was done using this variable, but I am now simply using ```event```.
I will nevertheless keep the ID, as it will surely be useful later, including event displays.
To be noted, the correct variable to use to associate TCs to cluster should be ```tc_multicluster_id```; I've created an issue #23.

2023-03-02 14:34 UTC, isehle approved these changes

2023-03-02 15:05 UTC, merged