[WIP] Scintillator geometry
bfonta/bye_splits pull request #26
Opened 2023-03-04 22:11 UTC by bfonta

**Description**

Add scintillator tiles to the geometry and extend the current silicon geometry to the CE-H (silicon-only and hybrid layers).

**Changes**

- Move geometry path configuration to the YAML format, following what has been done for event data.

2023-03-21 09:56 UTC, isehle submitted a review, later dismissed
As most of this PR focuses on geometry, I only quickly went through most of it, but it seems good to me! It's nice having all of the configuration settings in one file, and as far as I can tell, this should run well the size study and the associated app.

2023-03-24 11:22 UTC, mchiusi requested changes
Thanks Bruno. I think the new part is great!

2023-03-24 11:22 UTC, mchiusi commented on bye_splits/data_handle/geometry.py
> +    def provide(self, section='si', region=None, lrange=None):
Is there a reason why you set `section='si'`. I think it is better to put here `None` so that the entire HGCAL geometry is provided.

2023-03-24 14:15 UTC, bfonta commented on bye_splits/utils/params.py
>          d.update(cfg[task])
This is the point of the function. The ```base``` tasks is a just a convenient way to share common parameters across all tasks. 
If you are referring to the change of content in ```cfg```, that is fine, since its reference is lost as soon as the function returns.

2023-03-24 14:19 UTC, bfonta commented on config.yaml
> +    particles: photons
It is simply a default in case the user does not specify it in ```EventdataParticle```. I kept it since it seemed to be convenient for @isehle.

2023-03-24 16:02 UTC, mchiusi approved these changes

2023-03-24 16:20 UTC, isehle approved these changes
No issues on my side!

2023-03-24 16:23 UTC, merged