Common plotter class + addressing comments on new seeding method
bfonta/bye_splits pull request #43
Opened 2023-05-29 22:26 UTC by bfonta

This PR addresses all comments made to my first presentation on the new seeding on (U,V) coordinates, namely:
+ [X] use Clopper-Pearson intervals for efficiency errors instead of Poisson
+ [X] add TCs to efficiency plots but cutting the noise
    + I've applied a cylinder around the center of the shower
+ [X] visualize resolution distributions also with violin plots
+ [X] calculate the seeding efficiency having as reference the trigger cells around the generated particle, skipping the ROI step. This allows to factor the ROI out of seeding efficiency measurements.

Additionally, the PR includes a new class ```ChainPlotter``` which will hopefully represent the first step towards unifying the efficiency/resolution plots which are common to all our efforts.

Finally, I've added the number of events as an additional command line argument; this ensures all intermediate files stored are different for different number of input events, which is both convenient and safe (no confusion can arise in case one decides to run only part of the chain for a specific study).

2023-06-20 08:34 UTC, mchiusi requested changes

2023-06-20 08:34 UTC, mchiusi commented on bye_splits/tasks/validation.py
> +        sgen  = {k: pd.HDFStore(v, mode='r') for k,v in outgen.items()}
Is it necessary to use different libraries (`h5py` and `pandas`) to open the `HDF5` binary data format?
See next comment

2023-06-20 08:34 UTC, mchiusi commented on bye_splits/tasks/validation.py
> +        """Statistics collector for ROI seeding results."""
Please explain better which is the structure of this function (_at least_ in the PR). It is quite nested and it took me some time to understand the _dictionary of dictionary_

2023-06-20 08:34 UTC, mchiusi commented on bye_splits/tasks/validation.py
> +                colsseed = list(dfseed.attrs['columns'])
- Can you explain to me what are `ktc`, `ks`, `kt`, etc. 
 - How is `sseed[chain]` structured, i.e. how is the information packed in the `.hdf` files?

2023-06-20 10:01 UTC, bfonta commented on bye_splits/data_handle/data_process.py
> +        "good_tc_multicluster_id": "tc_multicluster_id",
Although currently we are not using it (besides on data processing steps), this id allows to associate trigger cells to clusters, and can thus be used for (at least) two things: 
 - Validation. Imagine a scenario where we develop a new clustering algorithm which performs differently than the current one. The most fine-grained why to study the differences would be to check, for each trigger cell, which cluster was it associated to, and compare it with our new custom method.
 - Event displays. The only way to display TCs association to "external" (CMSSW) clusters is to use this id, because the clustering was not done by us, and so we do not know the association *a priori*.

2023-06-20 10:06 UTC, bfonta commented on bye_splits/tasks/validation.py
> +        sgen  = {k: pd.HDFStore(v, mode='r') for k,v in outgen.items()}
This is a consequence of how those datasets were *written*. 
The question then becomes: why did I use different libraries to write the files? Ideally we would use only one, but ```pandas``` is easier to use and ```h5py``` is faster (since I can use ```numpy``` arrays directly). For instance, doing a ```groupby``` without pandas is tricky, but at the same time I want to avoid as much as possible using ```pandas``` dataframes inside the event loops of the reconstruction chain.
I would keep it this way, unless some volunteer wants to adapt everything to using ```hdf5``` only.

2023-06-20 10:16 UTC, bfonta commented on bye_splits/tasks/validation.py
> +                colsseed = list(dfseed.attrs['columns'])
In order:
- I thought the code was self-explanatory here; let me know how I can improve it otherwise. ```kseeds``` and ```ktc``` are the *keys* of, respectively, the seed and TC datasets (```keys()``` method). ```ks```, ```kt```, etc, are simply the iterators of those keys, *i.e.*, they point to a single key as should be clear from the ```for``` loop. Each key represents an event, hence the loop.
- ```chain``` refers to the type of chain you are running. Currently we have 2: the "standard", which I call "def" from "default", and the new u/v, coarse seeding one (called "roi"). With this structure you can plot quantities coming from different chains, which is very useful for comparisons, and was used for my u/v seeding slides. The structure of the hdf5 files did not change, I am now simply using a dictionary of those structures, where each element corresponds a different chain. See how I efined ```outseed```, for instance.

2023-06-20 11:45 UTC, isehle reviewed
Thanks for all the work you put into this! Besides my one question in `cluster.py`, this should all be fine for me. Would you also mind putting an example of how we can use the new plotting class in the PR? I.e., a command to run and its output, for example.

2023-06-20 12:24 UTC, bfonta commented on bye_splits/tasks/cluster.py
> +    for tck, seedk in tqdm(zip(tckeys, skeys), total=len(tckeys)):
```tqdm``` is just a Python package. It will thus not interfere at all with HTCondor; you just have to make sure you have it in the installation HTCondor has access to (which is likely the one available in the submission machine).
If you are worried, do a quick test on HTCondor with some prints within a ```tqdm``` loop.

2023-06-20 12:29 UTC, bfonta commented
@isehle See ```scripts/run_meta.py```, which should exemplify how to use the two new classes.
Please note that I am aware there are bits in the new classes that are not general, and some adaptations will likely be needed as more people use them and as we understand our needs. If there is something you do not like or think could be improved, now is the moment!

2023-06-20 22:50 UTC, bfonta commented on bye_splits/tasks/validation.py
> +        """Statistics collector for ROI seeding results."""
I see this is related to one of the other comments. I personally think there is no much sense in documenting code in a PR, since no one will be looking at the PR when reading code (just finding the PR takes time, and people are busy).
The paremeter ```chain_mode``` is clearly understood by looking at ```self._decode_modes(self, mode)``` (I've added a doc string there). ```pars``` means always the same in the repo, but I agree the name could be better, so I've changed it to ```cli_pars```, as a reference to the command line. I've also replace the 'roi' chain by the 'cs' ("coarse seeding") chain, since that's how it is called now.

2023-06-26 09:22 UTC, isehle approved these changes

2023-06-26 10:00 UTC, mchiusi approved these changes
This really looks great! I did fetch your branch to clarify some critical points - especially in the validation - by running the code in local. 
The display code in written using `bokeh` seems _at least to me_ much more convoluted that the same code in other libraries. Anyway I tested and it works.

2023-06-26 10:07 UTC, bfonta commented
@mchiusi I am not enforcing any library, you can use the one you prefer. I would just like that all the code right before plotting is the same for all of us. We can easily add some bokeh/plotly choice later on, as we are already doing in the geometry output.

2023-06-26 10:08 UTC, bfonta commented
I am keeping the three commits for clarity, since they are completely independent.

2023-06-26 10:08 UTC, merged